/* eslint-disable @next/next/no-img-element */
import '@/styles/globals.css'
import { useEffect } from 'react';
import type { AppProps } from 'next/app';
import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image';
import Script from 'next/script';
import CodeIcon from '../../public/code.png';
import styles from '@/styles/app.module.css';
import '../styles/scss/main.scss';
import {Gradient} from '../js/Gradient';
import Footer from '../../components/Footer/Footer';

export default function App({ Component, pageProps }: AppProps) {

  useEffect(() => {
    // Create instance
    const gradient = new Gradient()
    // Call `initGradient` with the selector to the canvas
    gradient.initGradient('#gradient-canvas');
  }, []);
  
  return (
    <>
      <Head>
        <title>NextJS Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="../js/Gradients" />
      <div className={styles.app}>
        <canvas id="gradient-canvas" data-js-darken-top data-transition-in />
        <nav className={styles.nav}>
          <Link className={styles.navLink} href="/">
            <Image
              src={CodeIcon}
              alt="code icon"
              width={48}
              height={48}
            />
          </Link>
        </nav>
        <Component {...pageProps} />
        <Footer />
      </div>
    </>
  )
}
