import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css';
//api request
import {GraphQLClient, gql} from 'graphql-request';
import BlogCard from 'components/BlogCard';

const graphcms = new GraphQLClient("https://api-us-west-2.hygraph.com/v2/cld63e58r1jec01um4zhf2rne/master");

// add what data we want to pull out
const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const {posts} = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  }
}


export default function Home({posts}:any) {
  return (
    <>
      <Head>
        <title>NextJS Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.cardGrid}>
          {posts.map((post:any) => (
            <BlogCard 
              key={post.id}
              title={post.title}
              author={post.author}
              datePublished={post.datePublished}
              slug={post.slug}
              coverPhoto={post.coverPhoto}
            />
          ))}
        </div>
      </main>
    </>
  )
}
